name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run linter checks
        run: npm run lint
      - name: Start NATS server
        run: docker-compose up -d
      - name: Run tests
        run: npm run test
